### ISSUE TITLE
Creative core seems to crash my game

### ISSUE THREAD

**Issue by Kamix13** [CreativeMD/CreativeCore#179] opened 2023-06-17 12:59 UTC
I wanted to download ItemPhysic mod, the mod without creative core doesn't seem to cause ANY problems (any problems not counting the notification about needing to add creativecore), but issues start, when I add creativecore to mod folder, I downloaded like 100 different versions of creative core for 1.19, and EVERY SINGLE ONE of them causes game to crash, the window of the game doesn't even appear on the screen and the only thing that happens is instant notification of the game crash in launcher
End code: 1

**Comment by CreativeMD** [comment] 2023-06-19 06:44
Make it game crash once more. Go to your minecraft folder, navigate to crash-reports and send me the newest crash-report here.

**Comment by Kamix13** [comment] 2023-06-22 12:37
I made it crash my game for like 5 times, but crash report refuses to be made, only thing I get is instant launcher reload with exit code 1

**Comment by Kamix13** [comment] 2023-06-22 12:38
The newest crash report is from two days ago

**Comment by VladislavBatura** [comment] 2023-06-24 16:24
Good evening, it seems, that i too have crashes with newest version of CreativeCore on Fabric with ItemPhysic and AmbientSounds. It crashes when i attempt to load a world, even not crashes, but just becomes "dead" process. Checked in logs, and game swears on "'material' is an invalid type". Crash log is included, hope it helps at least a little, have a good day.
[crash-2023-06-24_23.13.15-server.txt](https://github.com/CreativeMD/CreativeCore/files/11857618/crash-2023-06-24_23.13.15-server.txt)

**Comment by CreativeMD** [comment] 2023-07-11 10:54
@VladislavBatura Thanks for providing the details. This issue has been fixed for both forge and fabric in the newest version. It was caused by a recent change to adapt to the removal of block materials in 1.20.

**Closed as completed by CreativeMD** 2023-07-11 10:54 UTC
