### ISSUE TITLE
Unnecessary commands on tab completion

### ISSUE THREAD

**Issue by snakehugo** [CreativeMD/CreativeCore#184] opened 2023-07-27 00:14 UTC
There is 3 commands in the team\creative\creativecore\client\CreativeCoreClient.java that are soooo anoying.
I guess that's leftovers of your tests but there is no way to hide these for players that are not op on a server.

- /test-gui
- /test-client
- /cmdclientconfig

I know this mod is not supported anymore and even more in 1.16.5 but it would be really great to update the mod to 2.2.2 without these commands completions. Thanks a lot

**Comment by CreativeMD** [comment] 2023-07-27 06:46
The mod is still supported but for 1.20 that is. The test commands have been removed already in the newer versions. Sorry, but I will not fix this for 1.16.5. If you can try to update. Otherwise this mod is open source. The version for 1.16.5 is there as well. The problem is setting up the workspace, but that is still doable for CreativeCore (as it does not have any dependencies). I'm willing to assist and help out a little to do it, if you want to give it a try. You can still answer here, but I will close it for now.

**Closed as completed by CreativeMD** 2023-07-27 06:46 UTC
