### ISSUE TITLE
CreativeCore causing lagg.

### ISSUE THREAD

**Issue by CorbinCrow** [CreativeMD/CreativeCore#97] opened 2020-11-15 19:54 UTC
Hello,

This mod is causing lagg.
I play on my own vanilla server and have the creativecore mod installed since its needed for the ambientsounds mod.
When i have this installed and want to type a command in chat i get lagg as soon as i type "/".
This lagg is for me only. The people on my server don't notice a thing.
I was checking what caused this lagg and it seems it only happens when i have the CreativeCore mod installed.
This wasn't a problem when ambientsounds didn't require this core mod.

Greetings,
CorbinCrow

**Comment by CreativeMD** [comment] 2020-11-16 09:43
Weird, I cannot reproduce this issue with 1.16.4 and the newest versions. Maybe you run out of ram? You could press F3 and send me a screenshot of it.

**Comment by CreativeMD** [comment] 2020-11-23 10:21
This issue should be fixed in the newest version. Can you test it?

**Comment by CreativeMD** [comment] 2020-12-02 10:16
I will close this issue, if it still persists just let me know here.

**Closed as completed by CreativeMD** 2020-12-02 10:16 UTC
