### ISSUE TITLE
Incompatibility with Optifine Shades / Betweenlands

### ISSUE THREAD

**Issue by Elwood0** [CreativeMD/CreativeCore#42] opened 2019-06-13 14:12 UTC
### **Overview:** 

So Optifine has a feature with it shaders that allow for them to be enabled or disabled for certain dimensions using an empty folder called "world[Dimension ID]" This has worked brilliantly for other mods such as the Betweenlands, which carries its own shader. _However_, This seems to have been broken when using Creative Core, even without any of its subsidiaries.

### **Issue:** 

Normally with the setup mentioned, when using a portal, the shader switches from what Optifine is currently using to the one from the Betweenlands.

However, when Creative core is running, when you go through a portal, the screen freezes. The game is still running and audio, movement, and full control still are taking place in the game, but you can't see it, only the last frame before going through the portal.

### **How to Reproduce:** 

**1.** Run the latest versions of Forge (14.23.5.2838), Optifine, (1.12.2_HD_U_E3), the Betweenlands (v3.4.7), and Creative core (v1.9.45_mc1.12.2).

**2.** Use one of the following Shaders I linked below. You could use anyone from the internet, but you would have to add the "world[Dimension ID]" yourself.

[Shaders](https://github.com/CreativeMD/CreativeCore/files/3286548/Sildurs.Vibrant.Shaders.zip)

**3.** Launch the game and create a new world.

**4.** create a Betweenlands portal and attempt to go through.

**5.** Profit?

### **Conclusion:** 

If you have any questions about this, please let me know. I'm aware that this is a niche issue, but I hope it gets addressed soon. Thanks.

**Comment by CreativeMD** [comment] 2019-06-14 08:43
And you are 100% sure everything works fine when creativecore is not installed? (I don't see how CreativeCore could cause an issue like that).

**Comment by Elwood0** [comment] 2019-06-14 17:53
Yes, it's the only change I have been making between the two versions of Minecraft I have been testing. Sadly, I can't figure out the reason either. Is there some sort of config for Creative core I could test with, either as a separate file or within the mod jar itself?

**Comment by CreativeMD** [comment] 2019-06-28 10:59
Sorry for not responding earlier. Your issue is very very weird. Actually I'm completely lost, I have no idea how to fix it. I will try to reproduce it myself and then try to get in contact with the author of optifine.

One little idea, have you checked if the dimension id has changed? Maybe try it out with the nether or the end (because these ids never change).

**Comment by CreativeMD** [comment] 2019-06-28 13:56
Looks like stencil causes the issue. I have report this issue to the author of Optifine, we might be able to figure out a fix.

**Comment by Elwood0** [comment] 2019-06-28 16:27
Thanks for finding the issue. I hope it can be solved soon!

**Comment by Elwood0** [comment] 2019-07-10 19:14
Hi, just wanted to update saying that the recent updates to the mod sadly have not fixed the issue. This is in regards to version CreativeCore_v1.9.54_mc1.12.2.

**Comment by CreativeMD** [comment] 2019-07-10 19:19
Yeah, just follow the issue posted here earlier. Nothing has happened yet.

**Comment by kaporli** [comment] 2019-07-13 18:20
I don't have creative core installed but i'm encountering this issue? i googled my issue and this the only info i could find. Please help me ;-;

**Comment by CreativeMD** [comment] 2019-07-13 18:23
Currently there is no way to fix it, sorry :(

**Comment by kaporli** [comment] 2019-07-13 18:23
Wow that was fast, thank you for responding

**Comment by Elwood0** [comment] 2019-07-13 18:43
Kaporli, could you elaborate on your issue? It doesn't involve Creative Core, it may be fixable

**Comment by kaporli** [comment] 2019-07-13 18:45
Yeah i was dumb, i just had to disable BL's built in shaders

**Comment by Elwood0** [comment] 2019-07-13 19:20
Oh no, the method I created above allows you to use both BL shaders AND your regular shader in one Minecraft instance (though obviously not at the same time)

**Comment by Elwood0** [comment] 2019-07-13 19:21
https://github.com/sp614x/optifine/issues/2488#issuecomment-502237452

**Comment by CreativeMD** [comment] 2019-10-23 12:48
I guess I can close this issue, completely forgot it :D

**Closed as completed by CreativeMD** 2019-10-23 12:48 UTC
