### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by axin0452** [CreativeMD/CreativeCore#85] opened 2020-08-17 08:43 UTC
A frequently reported error
I don’t know what other information needs to be submitted
Please @me if needed

https://paste.ubuntu.com/p/kWFgFchwKw/

**Comment by CreativeMD** [comment] 2020-08-28 20:47
This is a duplicate of https://github.com/CreativeMD/LittleTiles/issues/455

**Closed as completed by CreativeMD** 2020-08-28 20:47 UTC

**Comment by Unbreakingslime** [comment] 2020-08-28 20:54
I have the last update of creative core...
